#### Consider the below code to answer further questions:
<br>import numpy as np
<br>list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
<br>array_list = np.array(object = list_)

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [2]:
print("Type of list_ Variable : ",type(list_))
print("Type of array_list Variable : ",type(array_list))
print("Data Type of elements in array_list Variable : ",array_list.dtype)

Type of list_ Variable :  <class 'list'>
Type of array_list Variable :  <class 'numpy.ndarray'>
Data Type of elements in array_list Variable :  <U1


### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [3]:
for i in list_:
    print(f"Type of list_ {i} Variable : {type(i)}")
    
for j in array_list:
    print(f"Type of array_list {j} Variable : {type(j)}")

Type of list_ 1 Variable : <class 'str'>
Type of list_ 2 Variable : <class 'str'>
Type of list_ 3 Variable : <class 'str'>
Type of list_ 4 Variable : <class 'str'>
Type of list_ 5 Variable : <class 'str'>
Type of array_list 1 Variable : <class 'numpy.str_'>
Type of array_list 2 Variable : <class 'numpy.str_'>
Type of array_list 3 Variable : <class 'numpy.str_'>
Type of array_list 4 Variable : <class 'numpy.str_'>
Type of array_list 5 Variable : <class 'numpy.str_'>


### Q3. Considering the following changes in the variable, array_list:<br>array_list = np.array(object = list_, dtype = int) <br>Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_ and array_list.
<br>Consider the below code to answer further questions:
<br>import numpy as np
<br>num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
<br>num_array = np.array(object = num_list)

In [4]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
array_list = np.array(object=list_,dtype=int)

In [5]:
for i in list_:
    print(f"Type of list_ {i} Variable : {type(i)}")
    
for j in array_list:
    print(f"Type of array_list {j} Variable : {type(j)}")

Type of list_ 1 Variable : <class 'str'>
Type of list_ 2 Variable : <class 'str'>
Type of list_ 3 Variable : <class 'str'>
Type of list_ 4 Variable : <class 'str'>
Type of list_ 5 Variable : <class 'str'>
Type of array_list 1 Variable : <class 'numpy.int64'>
Type of array_list 2 Variable : <class 'numpy.int64'>
Type of array_list 3 Variable : <class 'numpy.int64'>
Type of array_list 4 Variable : <class 'numpy.int64'>
Type of array_list 5 Variable : <class 'numpy.int64'>


### Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
<br>(ii) size

##### shape attribute:
The shape attribute of a NumPy array returns a tuple representing the dimensions of the array.
<br>It provides the number of elements along each axis (dimension) of the array.
<br>The length of the shape tuple corresponds to the number of dimensions (axes) of the array.
<br>The shape attribute is helpful in understanding the structure and dimensions of multi-dimensional arrays.
<br>The shape attribute can be accessed using the .shape notation.

##### size attribute:
The size attribute of a NumPy array returns the total number of elements present in the array.
<br>It represents the total size or length of the array when considering all its dimensions.
<br>The size attribute is similar to the len() function used for Python lists, but it works on multi-dimensional arrays as well.
<br>It is a scalar value (integer) representing the total count of elements in the array.
<br>The size attribute can be accessed using the .size notation.

In [6]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
num_array.shape

(2, 3)

In [8]:
num_array.size

6

### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

np.zeros() is a function used to create an array filled with zeros. 
<br>The function allows you to specify the shape and data type of the array you want to create. 
<br>It is particularly useful when you want to initialize an array with all elements set to zero.

In [9]:
arr = np.zeros((3,3))

In [10]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
arr.size

9

In [12]:
arr.shape

(3, 3)

### Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

np.eye() is a function used to create an identity matrix, which is a square matrix with ones on the main diagonal (from the top-left to the bottom-right) and zeros elsewhere. 
<br>The identity matrix is denoted by "I" or "𝐈" and has a unique property that when multiplied with any other matrix, it leaves the other matrix unchanged

In [13]:
arr1 = np.eye(5)

In [14]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
arr1.shape

(5, 5)

In [16]:
arr1.size

25